language: node_js

node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"

before_install:
  - "npm install typescript nyc mocha --global"

install:
  - "npm install"

script:
  - "npm test"

after_success:
  - npm install coveralls@~3.0.0 --global
  - npm run report-coverage

before_deploy:
  - "npm run clean"
  - "npm run build"

deploy:
  skip_cleanup: true
  provider: npm
  email: "arylo.open@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
